name: minimoodvoice
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow==2.13.0
      - numpy==1.24.3
      - librosa>=0.10.0
      - soundfile>=0.10.3
      - sounddevice>=0.4.6
      - streamlit==1.28.2
      - pandas>=1.3.0