name: autotagger_audio
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.16.6
  - pandas=1.1.5
  - scipy=1.4.1
  - h5py=2.10.0
  - ffmpeg
  - pip
  - pip:
      # Audio
      - musicnn==0.1.0
      - librosa==0.8.1
      - numba==0.49.1
      - llvmlite==0.32.1
      - soundfile==0.10.3.post1
      - audioread==2.1.9
      - resampy==0.2.2
      - joblib==0.17.0

      # Affichage / interface
      - matplotlib==3.3.4
      - streamlit==1.10.0